### #patches
GET https://api-146982620019.europe-west1.run.app/test/objects/ckrMCmhHYpXY4JfqPLrQ/patches/0

### #post object
POST https://api-146982620019.europe-west1.run.app/test/objects
accept: application/json  
Content-type: application/json; charset=UTF-8

{
  "type": "Boulder",
  "content": {
    "grade": "red"
  }
}
