### #patches
GET https://api-146982620019.europe-west1.run.app/test/objects/ckrMCmhHYpXY4JfqPLrQ/patches/0

### #post object
POST https://api-146982620019.europe-west1.run.app/test/objects
accept: application/json  
Content-type: application/json; charset=UTF-8

{
  "type": "Boulder",
  "content": {
    "grade": "red"
  }
}

### #get object
GET https://api-146982620019.europe-west1.run.app/test/objects/KdTqjNIlfKHHmI4Fej7C

### #patch object
PATCH https://api-146982620019.europe-west1.run.app/test/objects/KdTqjNIlfKHHmI4Fej7C
accept: application/json  
Content-type: application/json; charset=UTF-8

{
  "revision_id": 1,
  "operations": [
    {
      "type": "Set",
      "path": "grade",
      "value": "blue"
    }
  ]
}

### #get activeBoulders collection
GET https://api-146982620019.europe-west1.run.app/test/collection/activeBoulders

### #get accounts collection
GET https://api-146982620019.europe-west1.run.app/test/collection/accounts
