[package]
name = "otp"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
quickcheck = "1"
quickcheck_macros = "1"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.117"
