[package]
name = "all-o-stasis"
version = "0.1.0"
edition = "2021"

[dependencies]
otp = { path = "../../avers-otp", version = "0.1.0" }
axum = { version = "0.8.1", features = ["ws"] }
axum-extra = { version = "0.10.1", features = ["cookie", "typed-header"] }
chrono = "0.4.38"
cookie = "0.18"
firestore = "0.44"
futures = "0.3"
rand = "0.9.0"
sendgrid = "0.23.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.117"
sha2 = "0.10.8"
tokio = { version = "1.33.0", features = ["full", "macros", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1.39"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
