[package]
name = "all-o-stasis"
version = "0.1.0"
edition = "2021"

[dependencies]
otp = { path = "../../avers-otp", version = "0.1.0" }
axum = "0.8.1"
chrono = "0.4.38"
firestore = "0.44"
futures = "0.3"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.33.0", features = ["full", "macros", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1.39"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
